# This is a basic workflow to help you get started with Actions

name: generate animation

# Controls when the workflow will run
on:
  schedule: #execute every 6 hours
    - cron: "* */6 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: viniciussineza
          svg_out_path: dist/github-contribution-grid-snake.
          
      - name: push github-contribution-grid-snake.svg to the output branch
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
